version: "3"

vars:
  IMAGE_REPO: hkdarealest/devops-directive-docker-course-client-react-nginx
  IMAGE_TAG: 0.1.0

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .
  push-container-image:
    desc: Push container image to registry
    cmds:
      - docker push {{.IMAGE_REPO}}:{{.IMAGE_TAG}}

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  install:
    desc: install dependencies
    cmds:
      - npm install

  run:
    desc: Start react client
    cmds:
      - npm run dev
